<?php

namespace AppBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{
    public function showLastFiveAction(){
        $em     = $this->getEntityManager();
        $query  = $em->createQuery("SELECT b FROM AppBundle:Book b ORDER BY b.id DESC")->setMaxResults(5);
        $result = $query->getResult();
        return $result;
    }

    public function showAllAction(){
        $em     = $this->getEntityManager();
        $query  = $em->createQuery("SELECT b FROM AppBundle:Book b ORDER BY b.id DESC");
        $result = $query->getResult();
        return $result;
    }

    public function viewByGenre(string $name)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT b.name FROM AppBundle:Book b LEFT JOIN b.genre g WHERE g.name = :name ORDER BY b.id DESC ");
        $query->setParameter('name', $name);
        $result = $query->getResult();

        return $result;
    }
}
