<?php

namespace AppBundle\Repository;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends \Doctrine\ORM\EntityRepository
{
    public function checkGenrePromotion(string $genreName )
    {
        $today = new \DateTime();
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT p FROM AppBundle:Promotion p
                                          LEFT JOIN p.genre g
                                            WHERE g.name = :genreName AND p.endDate > :today
                                              ORDER BY p.discount DESC ");
        $query->setParameter(':genreName', $genreName);
        $query->setParameter(':today', $today);
        $query->setMaxResults(1);
        $result = $query->getResult();

        return $result;
    }
}
