<?php

namespace AppBundle\Repository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByBookId(int $bookId)
    {
        $em     = $this->getEntityManager();
        $query  = $em->createQuery("SELECT r
                                          FROM AppBundle:Review r 
                                            LEFT JOIN r.user u 
                                             LEFT JOIN r.book b 
                                              WHERE b.id = :id 
                                                ORDER BY r.id DESC");
        $query->setParameter('id', $bookId);
        $result = $query->getResult();

        return $result;

    }
}
